/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.BO.ContasBO;
import br.com.gabrielmelo.storemusic.BO.FuncionarioBO;
import br.com.gabrielmelo.storemusic.TO.ContasTO;
import br.com.gabrielmelo.storemusic.TO.FuncionarioTO;
import br.com.gabrielmelo.storemusic.TO.LoginTO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ListIterator;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gabriel Costa
 */
public class Form_Con_Contas extends javax.swing.JFrame {
    LoginTO lTO = new LoginTO();
    String ValidaAcesso;
    /**
     * Creates new form Form_Con_Contas
     */
    
     public String geraRelogio(){
      Date data = new Date();
      SimpleDateFormat horaF = new SimpleDateFormat("HH:mm:ss");
      String hora = horaF.format(data);
        return hora;
    }
    
    public void preencherTabela(){
        DefaultTableModel tabelaP = (DefaultTableModel)tblContas.getModel();
        ContasTO gmcp = new ContasTO();
        ContasBO gmcpBo = new ContasBO();
        ListIterator<ContasTO> lstiP = gmcpBo.getContas().listIterator();
            while(lstiP.hasNext()){
                gmcp = lstiP.next();
                tabelaP.addRow(new Object[]{gmcp.getCod_conta(),gmcp.getConta(),gmcp.getValor(),gmcp.getDtvenc(),gmcp.getFunc(),gmcp.getContador()});
            }
    }
    
    public void buscaNome(){
        DefaultTableModel tabelaP = (DefaultTableModel)tblContas.getModel();
        TableRowSorter sorter = null;
        sorter = new TableRowSorter<DefaultTableModel>(tabelaP);  
                      
        tblContas.setRowSorter(sorter);
        
        String text = txtConsulta.getText();  
        if (text.length() == 0) {  
          sorter.setRowFilter(null);  
        } else {  
          sorter.setRowFilter(RowFilter.regexFilter(text));  
        }     
     
}
    
    public Form_Con_Contas() {
        initComponents();
        preencherTabela();
    }
    
    public Form_Con_Contas(LoginTO lto,String nivelAcesso){
        initComponents();
        preencherTabela();
        lTO = lto;
        ValidaAcesso = nivelAcesso;
        String sessao = lTO.getUsuario();
        lblSessao.setText(""+sessao);
        timer1.start();
        lblHorario.setText(geraRelogio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSessao = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtConsulta = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 220, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 800, -1));

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id:", "Conta:", "Valor:", "Vencimento:", "Funcionário:", "Contador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 800, 131));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CONSULTA CONTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        lblSessao.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblSessao.setForeground(new java.awt.Color(0, 153, 0));
        lblSessao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário"));
        jPanel1.add(lblSessao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 129, 37));

        lblHorario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(0, 153, 0));
        lblHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horário"));
        jPanel1.add(lblHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 120, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 800, 90));

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked
        DefaultTableModel tabelaP = (DefaultTableModel)tblContas.getModel();
        int nro = tblContas.getSelectedRow();
        String id = String.valueOf(tblContas.getValueAt(nro, 0));
        
        int aux = Integer.parseInt(id);
        Form_Ins_Contas frmCont = new Form_Ins_Contas(aux,lTO,ValidaAcesso);
       
        frmCont.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblContasMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
       Form_Con_Geral frmProd = new Form_Con_Geral(lTO,ValidaAcesso);
        frmProd.show();
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        Form_Con_Geral frmGeral = new Form_Con_Geral(lTO,ValidaAcesso);
        frmGeral.show();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyReleased
        // TODO add your handling code here:
        buscaNome();
    }//GEN-LAST:event_txtConsultaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Con_Contas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblSessao;
    private javax.swing.JTable tblContas;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
