/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.TO.LoginTO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class Form_Ins_Geral extends javax.swing.JFrame {
    String ValidaAcesso;
    LoginTO lTO = new LoginTO();
    
    public String geraRelogio(){
      Date data = new Date();
      SimpleDateFormat horaF = new SimpleDateFormat("HH:mm:ss");
      String hora = horaF.format(data);
        return hora;
    }
    
    public Form_Ins_Geral() {
        initComponents();
    }

    public Form_Ins_Geral(LoginTO lto,String nivelAcesso) {
        initComponents();
        lTO = lto;
        String sessao = lTO.getUsuario();
        lblSessao.setText(""+sessao);
        
        ValidaAcesso = nivelAcesso;
        lblHorario.setText(geraRelogio());
        timer1.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        Painel_Ins_Geral = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblRetorna1 = new javax.swing.JLabel();
        lblSessao = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(637, 500));

        Painel_Ins_Geral.setBackground(new java.awt.Color(238, 220, 192));

        lblContas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_96.png"))); // NOI18N
        lblContas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContasMouseExited(evt);
            }
        });

        lblFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_96.png"))); // NOI18N
        lblFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseExited(evt);
            }
        });

        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_96.png"))); // NOI18N
        lblContador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContadorMouseExited(evt);
            }
        });

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_96.png"))); // NOI18N
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Funcionário");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fornecedor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contador");

        lblFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_96.png"))); // NOI18N
        lblFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseExited(evt);
            }
        });

        lblRetorna1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetorna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png"))); // NOI18N
        lblRetorna1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRetorna1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetorna1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRetorna1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRetorna1MouseExited(evt);
            }
        });

        lblSessao.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lblSessao.setForeground(new java.awt.Color(0, 153, 0));
        lblSessao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSessao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário"));

        lblHorario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(0, 153, 0));
        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horário"));

        lblProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_96.png"))); // NOI18N
        lblProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdutosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProdutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProdutosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Produtos");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Cadastro");

        javax.swing.GroupLayout Painel_Ins_GeralLayout = new javax.swing.GroupLayout(Painel_Ins_Geral);
        Painel_Ins_Geral.setLayout(Painel_Ins_GeralLayout);
        Painel_Ins_GeralLayout.setHorizontalGroup(
            Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(lblContas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetorna1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Ins_GeralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(31, 31, 31)))))
                .addGap(52, 52, 52))
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_Ins_GeralLayout.setVerticalGroup(
            Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(33, 33, 33)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Ins_GeralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRetorna1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu6.setText("Sair");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Ins_Geral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Ins_Geral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
if(ValidaAcesso.equals("Usuario") || ValidaAcesso.equals("usuario") ){
                Form_Menu_Simples frmSim = new Form_Menu_Simples(lTO,ValidaAcesso);
                frmSim.show();
                this.dispose();
            }else{
                Form_menu frmMenu = new Form_menu(lTO,ValidaAcesso);
                frmMenu.show();
                this.dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        // TODO add your handling code here:
        lblUsuario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_128.png")));
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        // TODO add your handling code here:
        lblUsuario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_96.png")));
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseEntered
        // TODO add your handling code here:
        lblContador.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_128.png")));
    }//GEN-LAST:event_lblContadorMouseEntered

    private void lblContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseExited
        // TODO add your handling code here:
        lblContador.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_96.png")));
    }//GEN-LAST:event_lblContadorMouseExited

    private void lblFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseEntered
        // TODO add your handling code here:
        lblFornecedor.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_128.png")));
    }//GEN-LAST:event_lblFornecedorMouseEntered

    private void lblFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseExited
        // TODO add your handling code here:
        lblFornecedor.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_96.png")));
    }//GEN-LAST:event_lblFornecedorMouseExited

    private void lblContasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseEntered
        // TODO add your handling code here:
        lblContas.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_128.png")));
    }//GEN-LAST:event_lblContasMouseEntered

    private void lblContasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseExited
        // TODO add your handling code here:
        lblContas.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_96.png")));
    }//GEN-LAST:event_lblContasMouseExited

    private void lblFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseEntered
        // TODO add your handling code here:
        lblFuncionario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_128.png")));
    }//GEN-LAST:event_lblFuncionarioMouseEntered

    private void lblFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseExited
        // TODO add your handling code here:
        lblFuncionario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_96.png")));
    }//GEN-LAST:event_lblFuncionarioMouseExited

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        Form_Ins_Cliente frmCli = new Form_Ins_Cliente(lTO,ValidaAcesso);
        frmCli.show();
        this.dispose();
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseClicked
        // TODO add your handling code here:
        Form_Ins_Cont frmCont = new Form_Ins_Cont(lTO,ValidaAcesso);
        frmCont.show();
        this.dispose();
    }//GEN-LAST:event_lblContadorMouseClicked

    private void lblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseClicked
        // TODO add your handling code here:
        Form_Ins_Forn frmForn = new Form_Ins_Forn(lTO,ValidaAcesso);
        frmForn.show();
        this.dispose();
    }//GEN-LAST:event_lblFornecedorMouseClicked

    private void lblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseClicked
        // TODO add your handling code here:
        Form_Ins_Func frmFunc = new Form_Ins_Func(lTO,ValidaAcesso);
        frmFunc.show();
        this.dispose();
    }//GEN-LAST:event_lblFuncionarioMouseClicked

    private void lblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseClicked
        // TODO add your handling code here:
        Form_Ins_Contas frmContas = new Form_Ins_Contas(lTO,ValidaAcesso);
        frmContas.show();
        this.dispose();
    }//GEN-LAST:event_lblContasMouseClicked

    private void lblRetorna1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetorna1MouseClicked
        // TODO add your handling code here:
            if(ValidaAcesso.equals("Usuario") || ValidaAcesso.equals("usuario") ){
                Form_Menu_Simples frmSim = new Form_Menu_Simples(lTO,ValidaAcesso);
                frmSim.show();
                this.dispose();
            }else{
                Form_menu frmMenu = new Form_menu(lTO,ValidaAcesso);
                frmMenu.show();
                this.dispose();
            }
        
    }//GEN-LAST:event_lblRetorna1MouseClicked

    private void lblRetorna1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetorna1MouseEntered
        // TODO add your handling code here:
        lblRetorna1.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_48.png")));
    }//GEN-LAST:event_lblRetorna1MouseEntered

    private void lblRetorna1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetorna1MouseExited
        // TODO add your handling code here:
        lblRetorna1.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png")));
    }//GEN-LAST:event_lblRetorna1MouseExited

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        lblHorario.setText(geraRelogio());
    }//GEN-LAST:event_timer1OnTime

    private void lblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutosMouseClicked
        // TODO add your handling code here:
        Form_Ins_Produtos frmProd = new Form_Ins_Produtos(lTO,ValidaAcesso);
        frmProd.show();
        this.dispose();
    }//GEN-LAST:event_lblProdutosMouseClicked

    private void lblProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutosMouseEntered
        // TODO add your handling code here:
        lblProdutos.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_128.png")));
    }//GEN-LAST:event_lblProdutosMouseEntered

    private void lblProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdutosMouseExited
        // TODO add your handling code here:
        lblProdutos.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_96.png")));
    }//GEN-LAST:event_lblProdutosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Ins_Geral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Ins_Geral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblRetorna1;
    private javax.swing.JLabel lblSessao;
    private javax.swing.JLabel lblUsuario;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
