/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.BO.ProdutosBO;
import br.com.gabrielmelo.storemusic.TO.LoginTO;
import br.com.gabrielmelo.storemusic.TO.ProdutosTO;
import br.com.gabrielmelo.storemusic.Utilitarios.ModificaString;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel Costa
 */
public class Form_Ins_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Form_Ins_Produtos
     */
    LoginTO lTO = new LoginTO();
    List<ProdutosTO> lstC = new LinkedList<ProdutosTO>();
    String ValidaAcesso;
    
    
     public void preencherCampo(int id){
        ProdutosTO c = new ProdutosTO();
         
        c.setCod_prod(id);
        ListIterator<ProdutosTO> lstiP = new ProdutosBO().getDadosProd(c).listIterator();
                    while(lstiP.hasNext())
        {
            c = lstiP.next();
            
            txtTipo.setText(c.getTipo());
            txtNome.setText(c.getNome());
            txtUnidade.setText(String.valueOf(c.getUnidade()));
            //txt.setText(c.getData());
            txtValor.setText(String.valueOf(c.getValor()));
            txtBarras.setText(String.valueOf(c.getCod_barras()));
            txtValor_custo.setText(String.valueOf(c.getValor_custo()));
        } 
    }
    //System.out.println("Prenche Campo"+c.getTipo()+""+c.getNome()+""+c.getUnidade()+""+c.getQuantidade()+""+c.getValor()+""+c.getCod_barras());                  

    public Form_Ins_Produtos() {
        initComponents();
         btnAltera.setVisible(false);
         btnExclui.setVisible(false);
        System.out.println("Construtor 1");
        txtId.setVisible(false);
        jLabel12.setVisible(false);
    }
    
     public Form_Ins_Produtos(LoginTO lto,String nivelAcresso){
         initComponents();
         lTO = lto;
         ValidaAcesso = nivelAcresso;
         btnAltera.setVisible(false);
         btnExclui.setVisible(false);
         System.out.println("Construtor 2");
         txtId.setVisible(false);
        jLabel12.setVisible(false);
     }
     
     public Form_Ins_Produtos(int _id,LoginTO lto,String nivelAcesso) {
                 
        initComponents();
        txtId.setText(String.valueOf(_id));
        preencherCampo(_id);
        lTO = lto;
        ValidaAcesso = nivelAcesso;
        btnCadastrar.setVisible(false);
       // btnMostrar.setVisible(false);
        System.out.println("Construtor 3");
        txtId.setVisible(false);
        jLabel12.setVisible(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAltera = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtUnidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBarras = new javax.swing.JTextField();
        txtValor_custo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnExclui = new javax.swing.JButton();
        lblVolta = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 220, 192));

        btnAltera.setBackground(new java.awt.Color(255, 255, 51));
        btnAltera.setText("ALTERAR");
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(51, 102, 255));
        btnMostrar.setText("BUSCAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(238, 220, 192));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 27, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("CÓDIGO:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 64, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TIPO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 121, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 152, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("UNIDADE:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 183, -1, -1));

        txtId.setEditable(false);
        txtId.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdCaretUpdate(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 62, 350, -1));
        jPanel2.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 119, 350, -1));
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 150, 350, -1));
        jPanel2.add(txtUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 181, 350, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Codigo de Barras");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 95, -1, -1));

        txtBarras.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBarrasCaretUpdate(evt);
            }
        });
        txtBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarrasActionPerformed(evt);
            }
        });
        jPanel2.add(txtBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 93, 350, -1));
        jPanel2.add(txtValor_custo, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 212, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Valor Custo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 214, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("VALOR:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 239, -1, -1));
        jPanel2.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 239, 350, -1));

        btnCadastrar.setBackground(new java.awt.Color(51, 255, 0));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExclui.setBackground(new java.awt.Color(255, 0, 0));
        btnExclui.setText("EXCLUIR");
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        lblVolta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png"))); // NOI18N
        lblVolta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblVolta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVolta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        // TODO add your handling code here:
        ProdutosTO c = new ProdutosTO();
        ProdutosBO cBO = new ProdutosBO();

        c.setCod_prod(Integer.parseInt(txtId.getText()));
        cBO.excluir(c);
    }//GEN-LAST:event_btnExcluiActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed
        // TODO add your handling code here:
        ProdutosTO c = new ProdutosTO();
        ProdutosBO cBO = new ProdutosBO();
        c.setCod_prod(Integer.parseInt(txtId.getText()));
        c.setTipo(txtTipo.getText());
        c.setNome(txtNome.getText());
        c.setUnidade(Float.parseFloat(txtUnidade.getText()));
        c.setValor(Float.parseFloat(txtValor.getText()));
        c.setValor_custo(Float.parseFloat(txtValor_custo.getText()));
        c.setCod_barras(txtBarras.getText());
        //executando no banco
        cBO.alterar(c);
    }//GEN-LAST:event_btnAlteraActionPerformed

    private void txtIdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdCaretUpdate
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdCaretUpdate

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        ProdutosTO c = new ProdutosTO();
        ProdutosBO cBO = new ProdutosBO();
        //c.setCod_prod(lstC.get(cmbProdutos.getSelectedIndex()).getCod_prod());
        c.setTipo(txtTipo.getText());
        c.setNome(txtNome.getText());
        c.setUnidade(Float.parseFloat(txtUnidade.getText()));
        c.setValor_custo(Float.parseFloat(txtValor_custo.getText()));
        c.setValor(Float.parseFloat(txtValor.getText()));
        c.setQuantidade(0);
        c.setCod_barras(txtBarras.getText());
        //long int x;
        //executando no banco
        cBO.salvar(c);

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        Form_Con_Produtos frmProd = new Form_Con_Produtos(lTO,ValidaAcesso);
        frmProd.show();
        this.dispose();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
       Form_Ins_Geral frmGeral = new Form_Ins_Geral(lTO,ValidaAcesso);
        frmGeral.show();
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txtBarrasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBarrasCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarrasCaretUpdate

    private void txtBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarrasActionPerformed

    private void lblVoltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltaMouseClicked
        // TODO add your handling code here:
        Form_Ins_Geral frmGeral = new Form_Ins_Geral(lTO,ValidaAcesso);
        frmGeral.show();
        this.dispose();
    }//GEN-LAST:event_lblVoltaMouseClicked

    private void lblVoltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltaMouseEntered
        // TODO add your handling code here:
        lblVolta.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_48.png")));
    }//GEN-LAST:event_lblVoltaMouseEntered

    private void lblVoltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltaMouseExited
        // TODO add your handling code here:
        lblVolta.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png")));
    }//GEN-LAST:event_lblVoltaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Ins_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Ins_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblVolta;
    private javax.swing.JTextField txtBarras;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUnidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValor_custo;
    // End of variables declaration//GEN-END:variables
}
