/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.Utilitarios.Grafico;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Gabriel Costa
 */
public class Form_Grafico_Teste extends javax.swing.JFrame {

   private CategoryDataset createDataset() {
        DefaultCategoryDataset ds = new DefaultCategoryDataset();
       
        Grafico gr = new Grafico();
        
        ds.addValue( 0, "a", "x" );  
        ds.addValue( 2.3, "a", "y" );  
  
          
  
        
        ds.addValue( 8, "b", "x" );  
        ds.addValue( 1.5, "b", "y" );  
  
        //ds.addValue( 0.5, "c", "x" );  
        //ds.addValue( 7, "c", "y" );  
        
            return ds;
    } 
   
   public void criaLinha(){
        CategoryDataset cds = createDataset();
        String titulo = "Gasto Mensal com Contas";
        String eixoy = "Valores";
        String txt_legenda = "Legenda:";
        boolean legenda = true;
        boolean tooltips = true;
        boolean urls = true;
        
        JFreeChart chart = ChartFactory.createLineChart(titulo,txt_legenda,eixoy, cds,PlotOrientation.HORIZONTAL, legenda, tooltips, urls );  
  
        CategoryItemRenderer renderer = chart.getCategoryPlot().getRenderer();  
        ChartPanel myChartPanel = new ChartPanel(chart, true);
        myChartPanel.setSize(jf.getWidth(),jf.getHeight());
        myChartPanel.setVisible(true);
        
        //renderer.setSeriesPaint( 0, new Color( 0, 255, 0 ) );  
        //renderer.setSeriesPaint( 1, Color.YELLOW );  
        //renderer.setSeriesPaint( 2, new Color( 0, 100, 155 ) );  
  
        //ChartPanel panel = new ChartPanel( chart );  
        jf.removeAll();
        jf.add(myChartPanel);
        jf.revalidate();
        jf.repaint();

   
   }
    public Form_Grafico_Teste() {
        initComponents();
        createDataset();
        criaLinha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jfLayout = new javax.swing.GroupLayout(jf);
        jf.setLayout(jfLayout);
        jfLayout.setHorizontalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jfLayout.setVerticalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Grafico_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Grafico_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Grafico_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Grafico_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Grafico_Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jf;
    // End of variables declaration//GEN-END:variables
}
