/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.TO.LoginTO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class Form_Con_Geral extends javax.swing.JFrame {
    String ValidaAcesso;
    LoginTO lTO = new LoginTO();
    
    public String geraRelogio(){
      Date data = new Date();
      SimpleDateFormat horaF = new SimpleDateFormat("HH:mm:ss");
      String hora = horaF.format(data);
        return hora;
    }
    
    public Form_Con_Geral() {
        initComponents();
    }
    
    public Form_Con_Geral(LoginTO lto,String nivelAcesso) {
        initComponents();
        lTO = lto;
        String sessao = lTO.getUsuario();
        lblSessao.setText(""+sessao);
        
        ValidaAcesso = nivelAcesso;
        lblHorario.setText(geraRelogio());
        timer1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        Painel_Ins_Geral = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblRetorna = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSessao = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblPordutos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Ins_Geral.setBackground(new java.awt.Color(238, 220, 192));
        Painel_Ins_Geral.setPreferredSize(new java.awt.Dimension(700, 491));

        lblContas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_96.png"))); // NOI18N
        lblContas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContasMouseExited(evt);
            }
        });

        lblFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_96.png"))); // NOI18N
        lblFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFornecedorMouseExited(evt);
            }
        });

        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_96.png"))); // NOI18N
        lblContador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContadorMouseExited(evt);
            }
        });

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_96.png"))); // NOI18N
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Funcionário");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fornecedor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contador");

        lblFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_96.png"))); // NOI18N
        lblFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFuncionarioMouseExited(evt);
            }
        });

        lblRetorna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png"))); // NOI18N
        lblRetorna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRetorna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetornaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRetornaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRetornaMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Consulta");

        lblSessao.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lblSessao.setForeground(new java.awt.Color(0, 153, 0));
        lblSessao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSessao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário"));

        lblHorario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(0, 153, 0));
        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horário"));

        lblPordutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPordutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_96.png"))); // NOI18N
        lblPordutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPordutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPordutosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPordutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPordutosMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Produtos");

        javax.swing.GroupLayout Painel_Ins_GeralLayout = new javax.swing.GroupLayout(Painel_Ins_Geral);
        Painel_Ins_Geral.setLayout(Painel_Ins_GeralLayout);
        Painel_Ins_GeralLayout.setHorizontalGroup(
            Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Ins_GeralLayout.createSequentialGroup()
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)))
                .addGap(50, 50, 50)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRetorna, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(114, 114, 114))))
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPordutos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addComponent(lblContas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Painel_Ins_GeralLayout.setVerticalGroup(
            Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))))
                .addGap(26, 26, 26)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContas, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(lblFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(lblPordutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Ins_GeralLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Ins_GeralLayout.createSequentialGroup()
                        .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)))
                .addGroup(Painel_Ins_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetorna, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(Painel_Ins_Geral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Operações");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Backup");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Segurança");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Sair");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseClicked
        // TODO add your handling code here:
        Form_Con_Contas frmContas = new Form_Con_Contas(lTO,ValidaAcesso);
        frmContas.show();
        this.dispose();
    }//GEN-LAST:event_lblContasMouseClicked

    private void lblContasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseEntered
        // TODO add your handling code here:
        lblContas.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_128.png")));
    }//GEN-LAST:event_lblContasMouseEntered

    private void lblContasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContasMouseExited
        // TODO add your handling code here:
        lblContas.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contas_96.png")));
    }//GEN-LAST:event_lblContasMouseExited

    private void lblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseClicked
        // TODO add your handling code here:
        Form_Con_Forn frmForn = new Form_Con_Forn(lTO,ValidaAcesso);
        frmForn.show();
        this.dispose();
    }//GEN-LAST:event_lblFornecedorMouseClicked

    private void lblFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseEntered
        // TODO add your handling code here:
        lblFornecedor.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_128.png")));
    }//GEN-LAST:event_lblFornecedorMouseEntered

    private void lblFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFornecedorMouseExited
        // TODO add your handling code here:
        lblFornecedor.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/fornecedor_96.png")));
    }//GEN-LAST:event_lblFornecedorMouseExited

    private void lblContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseClicked
        // TODO add your handling code here:
        Form_Con_Cont frmCont = new Form_Con_Cont(lTO,ValidaAcesso);
        frmCont.show();
        this.dispose();
    }//GEN-LAST:event_lblContadorMouseClicked

    private void lblContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseEntered
        // TODO add your handling code here:
        lblContador.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_128.png")));
    }//GEN-LAST:event_lblContadorMouseEntered

    private void lblContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseExited
        // TODO add your handling code here:
        lblContador.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/contador_96.png")));
    }//GEN-LAST:event_lblContadorMouseExited

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        Form_Con_Cliente frmCli = new Form_Con_Cliente(lTO,ValidaAcesso);
        frmCli.show();
        this.dispose();
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        // TODO add your handling code here:
        lblUsuario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_128.png")));
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        // TODO add your handling code here:
        lblUsuario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/usuario_96.png")));
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseClicked
        // TODO add your handling code here:
        Form_Con_Func frmFunc = new Form_Con_Func(lTO,ValidaAcesso);
        frmFunc.show();
        this.dispose();
    }//GEN-LAST:event_lblFuncionarioMouseClicked

    private void lblFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseEntered
        // TODO add your handling code here:
        lblFuncionario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_128.png")));
    }//GEN-LAST:event_lblFuncionarioMouseEntered

    private void lblFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuncionarioMouseExited
        // TODO add your handling code here:
        lblFuncionario.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/funcionario_96.png")));
    }//GEN-LAST:event_lblFuncionarioMouseExited

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void lblRetornaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetornaMouseClicked
        // TODO add your handling code here:
        System.err.println(""+ValidaAcesso);
            if(ValidaAcesso.equals("Usuario") || ValidaAcesso.equals("usuario") ){
                Form_Menu_Simples frmSim = new Form_Menu_Simples(lTO,ValidaAcesso);
                frmSim.show();
                this.dispose();
            }else{
                Form_menu frmMenu = new Form_menu(lTO,ValidaAcesso);
                frmMenu.show();
                this.dispose();
            }
        
    }//GEN-LAST:event_lblRetornaMouseClicked

    private void lblRetornaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetornaMouseEntered
        // TODO add your handling code here:
        lblRetorna.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_48.png")));
    }//GEN-LAST:event_lblRetornaMouseEntered

    private void lblRetornaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetornaMouseExited
        // TODO add your handling code here:
        lblRetorna.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/return_32.png")));
    }//GEN-LAST:event_lblRetornaMouseExited

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        lblHorario.setText(geraRelogio());
    }//GEN-LAST:event_timer1OnTime

    private void lblPordutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPordutosMouseEntered
        // TODO add your handling code here:
        lblPordutos.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_128.png")));
    }//GEN-LAST:event_lblPordutosMouseEntered

    private void lblPordutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPordutosMouseExited
        // TODO add your handling code here:
        lblPordutos.setIcon(new ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/produtos_96.png")));
    }//GEN-LAST:event_lblPordutosMouseExited

    private void lblPordutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPordutosMouseClicked
        // TODO add your handling code here:
        Form_Con_Produtos frmProd = new Form_Con_Produtos(lTO, ValidaAcesso);
        frmProd.show();
        this.dispose();
    }//GEN-LAST:event_lblPordutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Con_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Con_Geral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Ins_Geral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblPordutos;
    private javax.swing.JLabel lblRetorna;
    private javax.swing.JLabel lblSessao;
    private javax.swing.JLabel lblUsuario;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
