/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabrielmelo.storemusic.Formularios;

import br.com.gabrielmelo.storemusic.BO.LoginBO;
import br.com.gabrielmelo.storemusic.TO.LoginTO;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Costa
 */
public class LoginTeste extends javax.swing.JFrame {

    /**
     * Creates new form LoginTeste
     */
    public LoginTeste() {
        initComponents();
        java.awt.Image troca = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/gabrielmelo/storemusic/media/clave_sol_48.png"));
        ImageIcon img = new ImageIcon(troca);
        this.setIconImage(troca);
        //setIconImage(imageTitutoJanela.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        txtSenha2 = new javax.swing.JPasswordField();
        BgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setText("Clave de Sol");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 310, 120));

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 380, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 110, -1));

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 500, 30));

        txtSenha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenha2MouseClicked(evt);
            }
        });
        txtSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenha2KeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 380, -1));

        BgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gabrielmelo/storemusic/media/clave_de_sol_by_likano.jpg"))); // NOI18N
        getContentPane().add(BgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        LoginTO lto = new LoginTO();
        LoginBO lbo = new LoginBO();
        lto.setUsuario(txtLogin.getText());
        lto.setSenha(txtSenha2.getText());
        String nivelAcesso = null;
        boolean resul = lbo.login(lto.getUsuario(), lto.getSenha());
        try {

            if (resul = true) {

                nivelAcesso = lbo.validaAcesso();
                System.out.println("Dentro od IF:" + nivelAcesso);
                //JOptionPane.showMessageDialog(null, ""+);
                if (nivelAcesso.equals("Usuario") || nivelAcesso.equals("usuario")) {

                    Form_Menu_Simples frmSim = new Form_Menu_Simples(lto, nivelAcesso);
                    frmSim.show();
                    this.dispose();

                } else if (nivelAcesso.equals("Admin") || nivelAcesso.equals("admin")) {

                    Form_menu frmMenu = new Form_menu(lto, nivelAcesso);
                    frmMenu.show();
                    this.dispose();

                } else if (nivelAcesso.equals("Contador") || nivelAcesso.equals("contador")) {
                    System.out.println("contador vem pra caa");
                    Form_Rel_Geral frmCon = new Form_Rel_Geral(1, lto, nivelAcesso);
                    frmCon.show();
                    this.dispose();
                }

            } else {
                lblMsg.setText("Usuario ou Senha incorretos!");

            }

        } catch (Exception e) {
            lblMsg.setText("Usuario ou Senha incorretos!");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtSenha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha2MouseClicked

    }//GEN-LAST:event_txtSenha2MouseClicked

    private void txtSenha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenha2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginTO lto = new LoginTO();
            LoginBO lbo = new LoginBO();
            lto.setUsuario(txtLogin.getText());
            lto.setSenha(txtSenha2.getText());
            String nivelAcesso = null;
            boolean resul = lbo.login(lto.getUsuario(), lto.getSenha());
            try {

                if (resul = true) {

                    nivelAcesso = lbo.validaAcesso();
                    System.out.println("Dentro od IF:" + nivelAcesso);
                    //JOptionPane.showMessageDialog(null, ""+);
                    if (nivelAcesso.equals("Usuario") || nivelAcesso.equals("usuario")) {

                        Form_Menu_Simples frmSim = new Form_Menu_Simples(lto, nivelAcesso);
                        frmSim.show();
                        this.dispose();

                    } else if (nivelAcesso.equals("Admin") || nivelAcesso.equals("admin")) {

                        Form_menu frmMenu = new Form_menu(lto, nivelAcesso);
                        frmMenu.show();
                        this.dispose();

                    } else if (nivelAcesso.equals("Contador") || nivelAcesso.equals("contador")) {

                        Form_Rel_Geral frmCon = new Form_Rel_Geral(1, lto, nivelAcesso);
                        frmCon.show();
                        this.dispose();
                    }

                } else {
                    lblMsg.setText("Usuario ou Senha incorretos!");

                }

            } catch (Exception e) {
                lblMsg.setText("Usuario ou Senha incorretos!");

            }
        }

    }//GEN-LAST:event_txtSenha2KeyPressed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed

    }//GEN-LAST:event_txtLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha2;
    // End of variables declaration//GEN-END:variables
}
